const projects = {
  dumbassDonkeys: {
    api: "dumbass_donkeys",
    name: "Dumbass Donkey",
    floorPrice: 0.061,
    mintPriceSOL: 0.1,
    mintPriceUSDC: 33.62 * 0.1,
    mintDate: "2022-09-09",
    picture: "./dumbass_donkeys.webp",
    urlME: "//magiceden.io/marketplace/dumbass_donkeys",
  },
  lily: {
    api: "lily",
    name: "LILY",
    floorPrice: 0.686,
    mintPriceSOL: 3,
    mintPriceUSDC: 13.64 * 3,
    mintDate: "2022-11-18",
    picture: "./lily.png",
    urlME: "//magiceden.io/marketplace/lily",
  },
  taiyoPilots: {
    api: "taiyopilots",
    name: "Taiyo Pilot",
    floorPrice: 2.517,
    mintPriceSOL: 35,
    mintPriceUSDC: 9.76 * 35,
    mintDate: "2022-12-29",
    picture: "./taiyopilots.webp",
    urlME: "//magiceden.io/marketplace/taiyopilots",
  },
  ovols: {
    api: "elixir_ovols",
    name: "Ovol",
    floorPrice: 1.861,
    mintPriceSOL: 10,
    mintPriceUSDC: 14.29 * 10,
    mintDate: "2022-11-17",
    picture: "./ovols.webp",
    urlME: "//magiceden.io/marketplace/elixir_ovols",
  },
  primates: {
    api: "primates",
    name: "Primate",
    floorPrice: 1.776,
    mintPriceSOL: 4,
    mintPriceUSDC: 28.18 * 4,
    mintDate: "2022-06-14",
    picture: "./primates.webp",
    urlME: "//magiceden.io/marketplace/primates",
  },
  popheadz: {
    api: "popheadz",
    name: "POPHEAD",
    floorPrice: 0.202,
    mintPriceSOL: 3,
    mintPriceUSDC: 17.66 * 3,
    mintDate: "2022-11-11",
    picture: "./popheadz.webp",
    urlME: "//magiceden.io/marketplace/popheadz",
  },
  trippinApeTribe: {
    api: "trippin_ape_tribe",
    name: "Trippin' Ape",
    floorPrice: 0.752,
    mintPriceSOL: 3.5,
    mintPriceUSDC: 49.06 * 3.5,
    mintDate: "2022-05-24",
    picture: "./trippin_ape_tribe.webp",
    urlME: "//magiceden.io/marketplace/trippin_ape_tribe",
  },
  theBastards: {
    api: "the_bastards",
    name: "Bastard",
    floorPrice: 0.584,
    mintPriceSOL: 2.88,
    mintPriceUSDC: 20.95 * 2.88,
    mintDate: "2023-05-15",
    picture: "./the_bastards.png",
    urlME: "//magiceden.io/marketplace/the_bastards",
  },
  mindfolks: {
    api: "mindfolk",
    name: "Mindfolk",
    floorPrice: 0.174,
    mintPriceSOL: 1,
    mintPriceUSDC: 170.31 * 1,
    mintDate: "2022-01-01",
    picture: "mindfolk.webp",
    urlME: "//magiceden.io/marketplace/mindfolk",
  },
  peskyPenguins: {
    api: "pesky_penguins",
    name: "Pesky Penguin",
    floorPrice: 0.966,
    mintPriceSOL: 0.25,
    mintPriceUSDC: 154.26 * 0.25,
    mintDate: "2021-10-08",
    picture: "pesky_penguins.webp",
    urlME: "//magiceden.io/marketplace/pesky_penguins",
  },
};

export { projects };

// TEMPLATE
// lily: {
//   api: "",
//   name: "",
//   floorPrice: 0,
//   mintPriceSOL: 0,
//   mintPriceUSDC: 0,
//   mintDate: "",
//   picture: "",
//   urlME: "",
// },
